#+AUTHOR: Rory Hamaoka
#+DESCRIPTION: RH's emacs config
#+STARTUP: showeverything
#+OPTIONS: toc:t
#TOC: headlines 3

* Table of Contents :toc:
- [[#important-programs-to-load-first][IMPORTANT PROGRAMS TO LOAD FIRST]]
  - [[#adding-the-scripts-directory-to-path][Adding the scripts directory to path]]
  - [[#sourcing-the-scripts][Sourcing the scripts]]
- [[#all-the-icons][All the icons]]
- [[#backup][Backup]]
- [[#claude-code][Claude Code]]
- [[#company][Company]]
- [[#dashboard][Dashboard]]
- [[#diminish][Diminish]]
- [[#dired][Dired]]
- [[#elfeed][Elfeed]]
- [[#evil-mode][Evil Mode]]
- [[#flycheck][Flycheck]]
- [[#fonts][Fonts]]
  - [[#setting-the-font-face][Setting the Font Face]]
  - [[#zooming-inout][Zooming In/Out]]
- [[#general-keybindings][General Keybindings]]
- [[#git-programs][Git Programs]]
  - [[#git-time-machine][Git Time Machine]]
  - [[#magit][Magit]]
- [[#ivycouncil][Ivy(Council)]]
- [[#language-support][Language Support]]
  - [[#pyenv][Pyenv]]
- [[#markdown][Markdown]]
- [[#melpa][Melpa]]
- [[#minibuffer-escape][Minibuffer Escape]]
- [[#modeline][Modeline]]
- [[#neotree][Neotree]]
- [[#org-mode][Org Mode]]
  - [[#diminish-org-indent-mod][Diminish Org Indent Mod]]
  - [[#org-download][Org-download]]
  - [[#enable-table-of-contents][Enable Table Of Contents]]
  - [[#enable-org-bullets][Enable Org Bullets]]
  - [[#org-level-headers][Org Level Headers]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
- [[#pdf-tools-full-setup][PDF Tools Full Setup]]
- [[#pdf-org-tools][PDF Org Tools]]
- [[#projectile][Projectile]]
- [[#rainbow-delimitors][RAINBOW DELIMITORS]]
- [[#rainbow-mode][RAINBOW MODE]]
- [[#sane-defaults][Sane Defaults]]
- [[#shells-and-terminals][Shells and Terminals]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm-Toggle]]
- [[#sudo-edit][SUDO Edit]]
- [[#theme][THEME]]
- [[#tldr][TL;DR]]
- [[#transparency][Transparency]]
- [[#which-key][WHICH-KEY]]
- [[#custom-functions][Custom Functions]]

* IMPORTANT PROGRAMS TO LOAD FIRST

** Adding the scripts directory to path
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src

** Sourcing the scripts
#+begin_src emacs-lisp
(require 'elpaca-setup)  ;; The elpaca Package Manager
#+end_src

* All the icons
This is an icon set that can be used with dashboard, dired, ibuffer and other Emacs programs.
#+begin_src emacs-lisp
(use-package nerd-icons
  :ensure t
  :if (display-graphic-p))

(use-package nerd-icons-dired
  :hook (dired-mode . nerd-icons-dired-mode)) 

#+end_src

 
* Backup
By default, Emacs creates automatic backups of files in their original directories, such “file.el” and the backup “file.el~”.  This leads to a lot of clutter, so let’s tell Emacs to put all backups that it creates in the TRASH directory.

#+begin_src emacs-lisp
(setq backup-directory-alist '((".*" . "~/.local/share/Trash/files")))
#+end_src

* Claude Code
Automatically exports skill org files to SKILL.md with YAML frontmatter.
Only triggers for files with names ending in -skill.org.
Reads frontmatter values from #+SKILL_NAME and #+SKILL_DESC keywords.
#+begin_src emacs-lisp
(defun my/export-claude-skill ()
  "Export a -skill.org file to SKILL.md with YAML frontmatter.
 Only runs when the saved file ends with -skill.org."
  (when (and (eq major-mode 'org-mode)
             (buffer-file-name)
             (string-suffix-p "-skill.org"
                              (file-name-nondirectory (buffer-file-name))))
    (let* ((org-file (buffer-file-name))
           (dir (file-name-directory org-file))
           (tmp-file (expand-file-name "SKILL.md.tmp" dir))
           (output-file (expand-file-name "SKILL.md" dir))
           (skill-name (or (save-excursion
                             (goto-char (point-min))
                             (when (re-search-forward
                                    "^#\\+SKILL_NAME:\\s-*\\(.+\\)" nil t)
                               (match-string 1)))
                           "unnamed-skill"))
           (skill-desc (or (save-excursion
                             (goto-char (point-min))
                             (when (re-search-forward
                                    "^#\\+SKILL_DESC:\\s-*\\(.+\\)" nil t)
                               (match-string 1)))
                           "No description")))
      (org-export-to-file 'md tmp-file nil nil nil nil nil)
      (let ((md-content (with-temp-buffer
                          (insert-file-contents tmp-file)
                          (buffer-string)))
            (frontmatter (format "---\nname: %s\ndescription: %s\n---\n\n"
                                 skill-name skill-desc)))
        (with-temp-file output-file
          (insert frontmatter)
          (insert md-content))
        (delete-file tmp-file)
        (message "Claude skill exported to %s" output-file)))))

(add-hook 'after-save-hook #'my/export-claude-skill)
#+end_src




* Company
Company is a text completion framework for Emacs. The name stands for “complete anything”.  Completion will start automatically after you type a few letters. Use M-n and M-p to select, <return> to complete or <tab> to complete the common part.
#+begin_src emacs-lisp
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  :hook (after-init . global-company-mode))

(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))

#+end_src

* Dashboard
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.
#+begin_src emacs-lisp
(use-package dashboard
  :ensure t 
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.config/emacs/images/emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  :custom 
  (dashboard-modify-heading-icons '((recents . "file-text")
				      (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook)
  ;; Set a fefault projects folder for dashboard to find Projects
  (setq projectile-project-search-path '("~/projects/"))
  (setq projectile-switch-project-action #'projectile-dired))

#+end_src

* Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.  With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src


* Dired

#+begin_src emacs-lisp
;; Enable auto-creation of non-existent directories when using `C-x d`
(setq dired-create-destination-dirs t)

;; Enable auto-creation of non-existent directories when using `C-x d`
(setq dired-create-destination-dirs t)

;; Automatically clean up buffers after file operations (move/delete)
(setq dired-clean-up-buffers-too t)
(setq dired-clean-confirm-killing-deleted-buffers nil)


;; Enable auto-creation of non-existent directories when using `C-x d`
(setq dired-create-destination-dirs t)

;; Automatically clean up file-visiting buffers after move/delete
(setq dired-clean-up-buffers-too t)
(setq dired-clean-confirm-killing-deleted-buffers nil)

;; Auto-refresh Dired when files change
(setq global-auto-revert-non-file-buffers t)
(add-hook 'dired-mode-hook #'auto-revert-mode)

;; Run updatedb after file operations in Dired
(defun my/run-updatedb-after-dired ()
  "Run `updatedb` after Dired rename/move/delete."
  (start-process "updatedb" "*updatedb*" "sudo" "updatedb"))

(advice-add 'dired-do-rename :after #'my/run-updatedb-after-dired)
(advice-add 'dired-do-rename-regexp :after #'my/run-updatedb-after-dired)
(advice-add 'dired-do-delete :after #'my/run-updatedb-after-dired)

(use-package dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
  (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
  (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
  (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
  (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file))

#+end_src

* Elfeed
An RSS newsfeed reader for Emacs.  Move through the articles with ‘j/k’.  Move through the stories with ‘CTRL j/k’ when in other frame.
#+begin_src emacs-lisp
(use-package elfeed
  :config
  (setq elfeed-search-feed-face ":foreground #ffffff :weight bold"
        elfeed-feeds (quote
                       (("https://www.reddit.com/r/linux.rss" reddit linux)
                        ("https://www.reddit.com/r/commandline.rss" reddit commandline)
                        ("https://www.reddit.com/r/distrotube.rss" reddit distrotube)
                        ("https://www.reddit.com/r/emacs.rss" reddit emacs)
                        ("https://hackaday.com/blog/feed/" hackaday linux)
                        ("https://opensource.com/feed" opensource linux)
                        ("https://linux.softpedia.com/backend.xml" softpedia linux)
                        ("https://itsfoss.com/feed/" itsfoss linux)
                        ("https://www.zdnet.com/topic/linux/rss.xml" zdnet linux)
                        ("https://www.phoronix.com/rss.php" phoronix linux)
                        ("http://feeds.feedburner.com/d0od" omgubuntu linux)
                        ("https://www.computerworld.com/index.rss" computerworld linux)
                        ("https://www.networkworld.com/category/linux/index.rss" networkworld linux)
                        ("https://www.techrepublic.com/rssfeeds/topic/open-source/" techrepublic linux)
                        ("https://betanews.com/feed" betanews linux)
                        ("http://lxer.com/module/newswire/headlines.rss" lxer linux)
                        ("https://distrowatch.com/news/dwd.xml" distrowatch linux)))))
 

(use-package elfeed-goodies
  :init
  (elfeed-goodies/setup)
  :config
  (setq elfeed-goodies/entry-pane-size 0.5))
#+end_src


* Evil Mode
Evil is an extensible vi/vim layer for Emacs.  Because…let’s face it.  The Vim keybindings are just plain better.
#+begin_src emacs-lisp

;;(setq evil-want-C-u-scroll t)  ;; Must be set before evil-mode is loaded to enable Ctrl-u to use vim keybinding to scroll up half a page


;; Expands to: (elpaca evil (use-package evil :demand t))
   (use-package evil
       :init      ;; tweak evil's configuration before loading it
       (setq evil-want-integration t  ;; This is optional since it's already set to t by default.
             ;;(setq evil-want-C-u-scroll t) ;; Again here to be safe
             evil-want-keybinding nil
             evil-vsplit-window-right t
             evil-split-window-below t
             evil-undo-system 'undo-redo)  ;; Adds vim-like C-r redo functionality
       :config
       (evil-mode))

   (use-package evil-collection
     :after evil
     :config
     ;; Do not uncomment this unless you want to specify each and every mode
     ;; that evil-collection should works with.  The following line is here 
     ;; for documentation purposes in case you need it.  
     ;; (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer))
     (add-to-list 'evil-collection-mode-list 'help) ;; evilify help mode
     (evil-collection-init))


   (use-package evil-tutor)

   ;; Using RETURN to follow links in Org/Evil 
   ;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
   (with-eval-after-load 'evil-maps
     (define-key evil-motion-state-map (kbd "SPC") nil)
     (define-key evil-motion-state-map (kbd "RET") nil)
     (define-key evil-motion-state-map (kbd "TAB") nil))
   ;; Setting RETURN key in org-mode to follow links
     (setq org-return-follows-link  t)

      
#+end_src

* Flycheck
Install luacheck from your Linux distro’s repositories for flycheck to work correctly with lua files.  Install python-pylint for flycheck to work with python files.  Haskell works with flycheck as long as haskell-ghc or haskell-stack-ghc is installed.  For more information on language support for flycheck, [[https://www.flycheck.org/en/latest/languages.html][read this]].

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :init (global-flycheck-mode))

#+end_src

* Fonts
Defining the various fonts that Emacs will use.
** Setting the Font Face
#+begin_src emacs-lisp
(set-face-attribute 'default nil
  :font "JetBrains Mono"
  :height 110
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "Ubuntu"
  :height 120
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "JetBrains Mono"
  :height 110
  :weight 'medium)
;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil 
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

;;(set-frame-font "JetBrainsMono Nerd Font-12" nil t) ;; Nerd Font required to be set so icons show properly
(set-frame-font "FiraCode Nerd Font Mono-12" nil t) ;; Nerd Font required to be set so icons show properly


;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
(add-to-list 'default-frame-alist '(font . "JetBrains Mono-11"))

;; Uncomment the following line if line spacing needs adjusting.
(setq-default line-spacing 0.12)

#+end_src

** Zooming In/Out
You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out
#+begin_src emacs-lisp
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)

#+end_src

* General Keybindings

#+begin_src emacs-lisp

   (use-package general
     :config
     (general-evil-setup)

     ;; setup 'SPC' as the global leader key
   (general-create-definer dt/leader-keys
      :states '(normal visual emacs) ;; normal mode, insert mode, visual mode, emacs mode. Remove the state for insert mode or cannot place text
      :keymaps 'override
      :prefix "SPC" ;; set leader
      :global-prefix "M-SPC") ;; access leader in insert mode


    (dt/leader-keys
      "SPC" '(counsel-M-x :wk "Counsel M-x")
      "." '(find-file :wk "Find file")
      "=" '(perspective-map :wk "Perspective") ;; Lists all the perspective keybindings
      "TAB TAB" '(comment-line :wk "Comment lines")
      "u" '(universal-argument :wk "Universal argument"))

      
    (dt/leader-keys
       "b" '(:ignore t :wk "Bookmarks/Buffers")
       "b b" '(switch-to-buffer :wk "Switch to buffer")
       "b c" '(clone-indirect-buffer :wk "Create indirect buffer copy in a split")
       "b C" '(clone-indirect-buffer-other-window :wk "Clone indirect buffer in new window")
       "b d" '(bookmark-delete :wk "Delete bookmark")
       "b i" '(ibuffer :wk "Ibuffer")
       "b k" '(kill-current-buffer :wk "Kill current buffer")
       "b K" '(kill-some-buffers :wk "Kill multiple buffers")
       "b l" '(list-bookmarks :wk "List bookmarks")
       "b m" '(bookmark-set :wk "Set bookmark")
       "b n" '(next-buffer :wk "Next buffer")
       "b p" '(previous-buffer :wk "Previous buffer")
       "b r" '(revert-buffer :wk "Reload buffer")
       "b R" '(rename-buffer :wk "Rename buffer")
       "b s" '(basic-save-buffer :wk "Save buffer")
       "b S" '(save-some-buffers :wk "Save multiple buffers")
       "b w" '(bookmark-save :wk "Save current bookmarks to bookmark file"))

    (dt/leader-keys
       "d"   '(:ignore t :wk "Dired")
       "d d" '(dired :wk "Open dired")
       "d j" '(dired-jump :wk "Dired jump to current")
       "d n" '(neotree-dir :wk "Open directory in neotree")
       "d p" '(peep-dired :wk "Peep-dired")
       "d U" '((lambda () (interactive)
                (dired (concat "/sudo::" default-directory)))
                :wk "Open current dired directory as Root" ))

   (dt/leader-keys
       "e"   '(:ignore t :wk "Eshell/Evaluate")    
       "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
       "e d" '(eval-defun :wk "Evaluate defun containing or after point")
       "e e" '(eval-expression :wk "Evaluate and elisp expression")
       "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
       "e r" '(eval-region :wk "Evaluate elisp in region"))
  
   (dt/leader-keys
       "f"   '(:ignore t :wk "Files")    
       "f c" '((lambda () (interactive)
              (find-file "~/.config/emacs/config.org")) 
              :wk "Open emacs config.org")
       "f d" '(find-grep-dired :wk "Search for string in files in DIR")
       "f e" '((lambda () (interactive)
              (dired "~/.config/emacs/")) 
            :wk "Open user-emacs-directory in dired")
       "f g" '(counsel-grep-or-swiper :wk "Search for string current file")
       "f i" '((lambda () (interactive)
              (find-file "~/.config/emacs/init.el")) 
            :wk "Open emacs init.el")
       "f j" '(counsel-file-jump :wk "Jump to a file below current directory")
       "f k" '((lambda () (interactive)
              (find-file "~/Documents/projects/cmd_emacs/emacs_notes.org")) 
              :wk "Open emacs RH knoweldge base emacs_notes.org")
       "f l" '(counsel-locate :wk "Locate a file")
       "f r" '(counsel-recentf :wk "Find recent files")
       "f u" '(sudo-edit-find-file :wk "Sudo find file")
       "f U" '(sudo-edit :wk "Sudo edit file"))

   (dt/leader-keys
       "g"   '(:ignore t :wk "Git")    
       "g /" '(magit-displatch :wk "Magit dispatch")
       "g ." '(magit-file-displatch :wk "Magit file dispatch")
       "g a" '(magit-remote-add :wk "Magit add to a repository")
       "g b" '(magit-branch-checkout :wk "Switch branch")
       "g c" '(:ignore t :wk "Create") 
       "g c b" '(magit-branch-and-checkout :wk "Create branch and checkout")
       "g c c" '(magit-commit-create :wk "Create commit")
       "g c f" '(magit-commit-fixup :wk "Create fixup commit")
       "g C" '(magit-clone :wk "Clone repo")
       "g f" '(:ignore t :wk "Find") 
       "g f c" '(magit-show-commit :wk "Show commit")
       "g f f" '(magit-find-file :wk "Magit find file")
       "g f g" '(magit-find-git-config-file :wk "Find gitconfig file")
       "g F" '(magit-fetch :wk "Git fetch")
       "g g" '(magit-status :wk "Magit status")
       "g i" '(magit-init :wk "Initialize git repo")
       "g l" '(magit-log-buffer-file :wk "Magit buffer log")
       "g r" '(vc-revert :wk "Git revert file")
       "g s" '(magit-stage-file :wk "Git stage file")
       "g t" '(git-timemachine :wk "Git time machine")
       "g u" '(magit-stage-file :wk "Git unstage file"))
       
   (dt/leader-keys
       "h"   '(:ignore t :wk "Help")
       "h a" '(counsel-apropos :wk "Apropos")
       "h b" '(describe-bindings :wk "Describe bindings")
       "h c" '(describe-char :wk "Describe character under cursor")
       "h d" '(:ignore t :wk "Emacs documentation")
       "h d a" '(about-emacs :wk "About Emacs")
       "h d d" '(view-emacs-debugging :wk "View Emacs debugging")
       "h d f" '(view-emacs-FAQ :wk "View Emacs FAQ")
       "h d m" '(info-emacs-manual :wk "The Emacs manual")
       "h d n" '(view-emacs-news :wk "View Emacs news")
       "h d o" '(describe-distribution :wk "How to obtain Emacs")
       "h d p" '(view-emacs-problems :wk "View Emacs problems")
       "h d t" '(view-emacs-todo :wk "View Emacs todo")
       "h d w" '(describe-no-warranty :wk "Describe no warranty")
       "h e" '(view-echo-area-messages :wk "View echo area messages")
       "h f" '(describe-function :wk "Describe function")
       "h F" '(describe-face :wk "Describe face")
       "h g" '(describe-gnu-project :wk "Describe GNU Project")
       "h i" '(info :wk "Info")
       "h I" '(describe-input-method :wk "Describe input method")
       "h k" '(describe-key :wk "Describe key")
       "h l" '(view-lossage :wk "Display recent keystrokes and the commands run")
       "h L" '(describe-language-environment :wk "Describe language environment")
       "h m" '(describe-mode :wk "Describe mode")
       "h r" '(:ignore t :wk "Reload")
       "h r r" '((lambda () (interactive)
                (load-file "~/.config/emacs/init.el")
                (ignore (elpaca-process-queues)))
                :wk "Reload emacs config")
       "h t" '(load-theme :wk "Load theme")
       "h v" '(describe-variable :wk "Describe variable")
       "h w" '(where-is :wk "Prints keybinding for command if set")
       "h x" '(describe-command :wk "Display full documentation for command"))
  
   (dt/leader-keys
       "m"   '(:ignore t :wk "Org")
       "m a" '(org-agenda :wk "Org agenda")
       "m e" '(org-export-dispatch :wk "Org export dispatch")
       "m i" '(org-toggle-item :wk "Org toggle item")
       "m t" '(org-todo :wk "Org todo")
       "m B" '(org-babel-tangle :wk "Org babel tangle")
       "m T" '(org-todo-list :wk "Org todo list"))

   (dt/leader-keys
       "m b" '(:ignore t :wk "Tables")
       "m b -" '(org-table-insert-hline :wk "Insert hline in table"))

   (dt/leader-keys
       "m d" '(:ignore t :wk "Date/deadline")
       "m d t" '(org-time-stamp :wk "Org time stamp"))

   (dt/leader-keys
       "o"   '(:ignore t :wk "Open")
       "o d" '(dashboard-open :wk "Dashboard")
       "o e" '(elfeed :wk "Elfeed RSS")
       "o f" '(make-frame :wk "Open buffer in new frame")
       "o F" '(select-frame-by-name :wk "Select frame by name")
       "o p" '(pdf-view-mode :wk "Open PDF"))


   (dt/leader-keys
       "p"   '(:ignore t :wk "Python")
       "p v" '(pyvenv-activate :wk "Set python .venv"))

   (dt/leader-keys
       "s"   '(:ignore t :wk "Search")
       "s d" '(dictionary-search :wk "Search dictionary")
       "s m" '(man :wk "Man pages")
       "s t" '(tldr :wk "Lookup TLDR docs for a command")
       "s w" '(woman :wk "Similar to man but doesn't require man"))



   (dt/leader-keys
       "t"   '(:ignore t :wk "Toggle")
       "t e" '(eshell-toggle :wk "Toggle eshell")
       "t f" '(flycheck-mode :wk "Toggle flycheck")
       "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
       "t n" '(neotree-toggle :wk "Toggle neotree file viewer")
       "t o" '(org-mode :wk "Toggle org mode")    
       "t r" '(rainbow-mode :wk "Toggle rainbow mode")
       "t t" '(visual-line-mode :wk "Toggle truncated lines")
       "t v" '(vterm-toggle :wk "Toggle vterm"))

   (dt/leader-keys
       "w"   '(:ignore t :wk "Windows")
       ;; Window splits
       "w c" '(evil-window-delete :wk "Close window")
       "w n" '(evil-window-new :wk "New window")
       "w s" '(evil-window-split :wk "Horizontal split window")
       "w v" '(evil-window-vsplit :wk "Vertical split window")
       ;; Window motions
       "w h" '(evil-window-left :wk "Window left")
       "w j" '(evil-window-down :wk "Window down")
       "w k" '(evil-window-up :wk "Window up")
       "w l" '(evil-window-right :wk "Window right")
       "w w" '(evil-window-next :wk "Goto next window")
       ;; Move Windows
       "w H" '(buf-move-left :wk "Buffer move left")
       "w J" '(buf-move-down :wk "Buffer move down")
       "w K" '(buf-move-up :wk "Buffer move up")
       "w L" '(buf-move-right :wk "Buffer move right"))

       )
   
#+end_src

* Git Programs


** Git Time Machine
git-timemachine is a program that allows you to move backwards and forwards through a file’s commits.  ‘SPC g t’ will open the time machine on a file if it is in a git repo.  Then, while in normal mode, you can use ‘CTRL-j’ and ‘CTRL-k’ to move backwards and forwards through the commits.
Magit requires transient. If the installed version of transient is too old, Magit will not load and will throw an error in emacs
#+begin_src emacs-lisp
    (use-package transient)
      

    (use-package git-timemachine      
      :hook (evil-normalize-keymaps . git-timemachine-hook)
      :config
        (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
        (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
    )
#+end_src

** Magit
Magit is a full-featured git client for Emacs. For some reason, this wouldn't install using elpaca, so I had to use use package-list-packages to install Magit

#+begin_src emacs-lisp
(use-package magit)
  
#+end_src

* Ivy(Council)
  Ivy, a generic completion mechanism for Emacs.
  Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
  Ivy-rich allows us to add descriptions alongside the commands in M-x.
#+begin_src emacs-lisp
(use-package counsel
  :after ivy
  :diminish
  :config 
    (counsel-mode)
    (setq ivy-initial-inputs-alist nil)) ;; removes starting ^ regex in M-x

(use-package ivy
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :diminish
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :config
  (ivy-mode))

(use-package all-the-icons-ivy-rich
  :ensure t
  :init (all-the-icons-ivy-rich-mode 1))

(use-package ivy-rich
  :after ivy
  :ensure t
  :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer))

#+end_src

* Language Support
Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK, C, C++, Fortran, Icon, IDL (CORBA), IDLWAVE, Java, Javascript, M4, Makefiles, Metafont, Modula2, Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby, Simula, SQL, Tcl, Verilog, and VHDL.  Other languages will require you to install additional modes.
#+begin_src emacs-lisp
;;(use-package haskell-mode)
;;(use-package lua-mode)
;;(use-package php-mode)

#+end_src

#+begin_src emacs-lisp
;; Basic C Programming Setup

;; Enable CC Mode for C programming
(use-package cc-mode
  :ensure t)  ;; Ensure cc-mode is installed

;; Set up basic C mode settings
(add-hook 'c-mode-hook
          (lambda ()
            (setq c-basic-offset 4)  ;; Indentation level
            (setq tab-width 4)))      ;; Tab width

#+end_src



** Pyenv
Emacs helper package to make Emacs aware of a virtual enviroment. Once Emacs knows about the venv, running the python interpreter is simple
#+begin_src emacs-lisp
(use-package pyvenv
  :ensure t)

#+end_src

* Markdown
#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure t
  :mode ("\\.md\\ . markdown-mode"))

#+end_src


* Melpa
MELPA (Milkypostman’s Emacs Lisp Package Archive) is one of the main package repositories for Emacs. Think of it as an “app store” for Emacs Lisp packages. 
#+begin_src 
(require 'package)

;; Add MELPA repository
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

;; Initialize package system
(package-initialize)

;; Always refresh package list to see latest packages like vterm
(package-refresh-contents)

#+end_src






* Minibuffer Escape
By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.
#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)

#+end_src

* Modeline
The modeline is the bottom status bar that appears in Emacs windows.  While you can create your own custom modeline, why go to the trouble when Doom Emacs already has a nice modeline package available.  For more information on what is available to configure in the Doom modeline, check out: Doom Modeline
#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 35      ;; sets modeline height
        doom-modeline-bar-width 5    ;; sets right bar width
        doom-modeline-persp-name t   ;; adds perspective name to modeline
        doom-modeline-persp-icon t)) ;; adds folder icon next to persp name
#+end_src

* Neotree
Neotree is a file tree viewer.  When you open neotree, it jumps to the current file thanks to neo-smart-open.  The neo-window-fixed-size setting makes the neotree width be adjustable.  NeoTree provides following themes: classic, ascii, arrow, icons, and nerd.  Theme can be config’d by setting “two” themes for neo-theme: one for the GUI and one for the terminal.  I like to use ‘SPC t’ for ‘toggle’ keybindings, so I have used ‘SPC t n’ for toggle-neotree.
| COMMAND        | DESCRIPTION               | KEYBINDING |
| neotree-toggle | Toggle neotree            | SPC t n    |
| neotree-dir    | Open directory in neotree | SPC d n    |

#+begin_src emacs-lisp
(use-package neotree
  :after nerd-icons
  :config
  (setq neo-smart-open t
        neo-show-hidden-files t
        neo-window-width 55
        neo-window-fixed-size nil
        inhibit-compacting-font-caches t
        projectile-switch-project-action 'neotree-projectile-action) 
        ;; truncate long file names in neotree
        (add-hook 'neo-after-create-hook
           #'(lambda (_)
               (with-current-buffer (get-buffer neo-buffer-name)
                 (setq truncate-lines t)
                 (setq word-wrap nil)
                 (make-local-variable 'auto-hscroll-mode)
                 (setq auto-hscroll-mode nil)))))

#+end_src



* Org Mode
** Diminish Org Indent Mod
e
#+begin_src emacs-lisp
(eval-after-load 'org-indent '(diminish 'org-indent-mode))
#+end_src

** Org-download
org-download is an Emacs package that makes it super easy to save and insert images into Org-mode documents. For example, you can drag an image file into an Org buffer and it will save the image to a folder and insert the proper link automatically.

| Common Command              | Action                                               |
| M-x org-download-clipboard  | Paste an image from your clipboard into the org file |
| M-x org-download-screenshot | Take a screenshot and insert it                      |                          

#+begin_src emacs-lisp
(elpaca org-download
  ;; Optional: pin to a stable commit or branch, otherwise latest
  ;; :ref "commit-sha-or-branch-name"
  ;; Configuration after install
  (with-eval-after-load 'org
    (add-hook 'org-mode-hook #'org-download-enable)
    (setq org-download-image-dir "./images"
          org-download-screenshot-method "scrot -s %s"
          org-download-link-format "[[file:%s]]")))

#+end_src





** Enable Table Of Contents
#+begin_src emacs-lisp
(use-package toc-org
    :ensure t
    :config
       (setq org-export-headline-levels 4
             toc-org-max-depth 4)
    :hook (org-mode . toc-org-enable))
#+end_src

** Enable Org Bullets
#+begin_src emacs-lisp
;;Org-bullets gives us attractive bullets rather than astricks
;;Rewrite from above so that all .org files utilize this configuration
(use-package org-bullets
     :ensure t
     :hook (org-mode . org-bullets-mode))

#+end_src

** Org Level Headers
#+begin_src emacs-lisp
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.7))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.4))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.3))))
 '(org-level-6 ((t (:inherit outline-5 :height 1.2))))
 '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
#+end_src

** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled. Org-tempo allows for '<s' followed by TAB to expand to begin_src tag. Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
| <a                     | ’#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT' |
| <c                     | ’#+BEGIN_CENTER’ … ‘#+END_CENTER’       |
| <C                     | ’#+BEGIN_COMMENT’ … ‘#+END_COMMENT’     |
| <e                     | ’#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE'     |
| <E                     | ’#+BEGIN_EXPORT’ … ‘#+END_EXPORT’       |
| <h                     | ’#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’  |
| <l                     | #+BEGIN_EXPORT latex’ … ‘#+END_EXPORT'  |
| <q                     | ’#+BEGIN_QUOTE’ … ‘#+END_QUOTE          |
| <s                     | ’#+BEGIN_SRC’ … ‘#+END_SRC              |
| <v                     | '#+BEGIN_VERSE' ... '#+END_VERSE'       |

#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

* PDF Tools Full Setup
#+begin_src emacs-lisp
(use-package pdf-tools
  :ensure t
  :mode ("\\.pdf\\'" . pdf-view-mode)
  :init
  (setq pdf-view-use-scaling t
        pdf-view-use-imagemagick nil)
  :config
  (setq pdf-view-incompatible-modes '(display-line-numbers-mode))
  (pdf-tools-install t)
  (setq pdf-view-display-size 'fit-page)

  ;; Enable annotation minor mode
  (add-hook 'pdf-view-mode-hook #'pdf-annot-minor-mode)

  ;; --------------------------------
  ;; Custom copy function
  ;; --------------------------------
  (defun my/pdf-copy-text ()
    "Copy the currently selected region text in pdf-view."
    (interactive)
    (if (pdf-view-active-region-p)
        (let ((text (mapconcat #'identity (pdf-view-active-region-text) "\n")))
          (kill-new text)
          (pdf-view-deactivate-region)
          (message "Copied: %s" (truncate-string-to-width text 60)))
      (message "No region selected. Use mouse to select text first.")))

  ;; --------------------------------
  ;; Evil keybindings for pdf-view
  ;; --------------------------------
  (with-eval-after-load 'evil
    (evil-define-key 'normal pdf-view-mode-map
      (kbd "j")  #'pdf-view-next-line-or-next-page
      (kbd "k")  #'pdf-view-previous-line-or-previous-page
      (kbd "h")  #'image-backward-hscroll
      (kbd "l")  #'image-forward-hscroll
      (kbd "gg") #'pdf-view-first-page
      (kbd "G")  #'pdf-view-last-page
      (kbd "/")  #'isearch-forward
      (kbd "y")  #'my/pdf-copy-text)

    ;; Pass annotation keys through Evil so pdf-annot-minor-mode works
    (evil-define-key 'normal pdf-annot-minor-mode-map
      (kbd "a t") #'pdf-annot-add-text-annotation
      (kbd "a h") #'pdf-annot-add-highlight-markup-annotation
      (kbd "a u") #'pdf-annot-add-underline-markup-annotation
      (kbd "a s") #'pdf-annot-add-strikeout-markup-annotation
      (kbd "a d") #'pdf-annot-delete
      (kbd "a l") #'pdf-annot-list-annotations))

  ;; --------------------------------
  ;; Non-evil fallback bindings
  ;; --------------------------------
  (define-key pdf-view-mode-map (kbd "C-c C-c") #'my/pdf-copy-text)
  (define-key pdf-view-mode-map (kbd "M-w")     #'my/pdf-copy-text))
#+end_src

* PDF Org Tools
#+begin_src emacs-lisp
(use-package org-pdftools
  :ensure t
  :hook (org-mode . org-pdftools-setup-link)
  :init
  (with-eval-after-load 'org
    (org-pdftools-setup-link))
  :config
  (setq org-pdftools-root-dir "~/datasheets/")
  (setq org-pdftools-search-string-separator "??"))

(global-set-key (kbd "C-c l") #'org-store-link)
#+end_src


* Projectile
[[https://github.com/nex3/perspective-el][Projectile]] is a project interaction library for Emacs.  It should be noted that many projectile commands do not work if you have set “fish” as the “shell-file-name” for Emacs.  I had initially set “fish” as the “shell-file-name” in the Vterm section of this config, but oddly enough I changed it to “bin/sh” and projectile now works as expected, and Vterm still uses “fish” because my default user “sh” on my Linux system is “fish”.

#+begin_src emacs-lisp
(use-package projectile
  :config
  (projectile-mode 1))

#+end_src


* RAINBOW DELIMITORS
Adding rainbow coloring to parentheses.
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
         (clojure-mode . rainbow-delimiters-mode)))

#+end_src

* RAINBOW MODE
Display the actual color as a background for any hex color value (ex. #ffffff).  The code block below enables rainbow-mode in all programming modes (prog-mode) as well as org-mode, which is why rainbow works in this document.
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :diminish
    :hook ((org-mode . rainbow-mode)
  	 (prog-mode . rainbow-mode)))
#+end_src

* Sane Defaults
The following settings are simple modes that are enabled (or disabled) so that Emacs functions more like you would expect a proper editor/IDE to function. 
#+begin_src emacs-lisp

(delete-selection-mode 1)    ;; You can select text and delete it by typing.
(electric-indent-mode -1)    ;; Turn off the weird indenting that Emacs does by default.
(electric-pair-mode 1)       ;; Turns on automatic parens pairing
;; The following prevents <> from auto-pairing when electric-pair-mode is on.
;; Otherwise, org-tempo is broken when you try to <s TAB...
(add-hook 'org-mode-hook (lambda ()
           (setq-local electric-pair-inhibit-predicate
                   `(lambda (c)
                  (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
(global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
(global-display-line-numbers-mode 1) ;; Display line numbers
(column-number-mode 1)       ;; Enable column numbers
(global-visual-line-mode t)  ;; Enable truncated lines
(menu-bar-mode -1)           ;; Disable the menu bar 
(scroll-bar-mode -1)         ;; Disable the scroll bar
(tool-bar-mode -1)           ;; Disable the tool bar
(setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
  
#+end_src

* Shells and Terminals
In my configs, all of my shells (bash, fish, zsh and the ESHELL) require my shell-color-scripts-git package to be installed.  On Arch Linux, you can install it from the AUR.  Otherwise, go to my shell-color-scripts repository on GitLab to get it.
** Eshell
#+begin_src emacs-lisp
(use-package eshell-toggle
  :custom
  (eshell-toggle-size-fraction 3)
  (eshell-toggle-use-projectile-root t)
  (eshell-toggle-run-command nil)
  (eshell-toggle-init-function #'eshell-toggle-init-ansi-term))

  (use-package eshell-syntax-highlighting
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))

  ;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.
  ;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
  ;; eshell-aliases-file -- sets an aliases file for the eshell.

  (setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
        eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
        eshell-history-size 5000
        eshell-buffer-maximum-lines 5000
        eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t
        eshell-destroy-buffer-when-process-dies t
        eshell-visual-commands '("bash" "fish" "htop" "ssh" "top" "zsh"))

#+end_src

** Vterm
Vterm is a terminal emulator within Emacs.  The ‘shell-file-name’ setting sets the shell to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm.  By default, the shell is set to 'zsh’ but could change it to ‘fish’ or ‘zsh’ if you prefer.
#+begin_src emacs-lisp
(use-package vterm
  :ensure t
  :config
  ;; -------------------------------
  ;; Basic shell settings
  ;; -------------------------------
  ;; Set default shell to zsh if available, otherwise bash
  (setq shell-file-name (if (file-exists-p "/bin/zsh")
                          "/bin/zsh"
                        "/bin/bash"))
  ;; Use zsh in vterm if available, otherwise bash
  (setq vterm-shell (if (file-exists-p "/bin/zsh")
                      "/bin/zsh"
                    "/bin/bash")) ;; Set default shell to zsh
  ;;(setq shell-file-name "/bin/zsh")
  ;; Use zsh in vterm
  ;;(setq vterm-shell "/bin/zsh")
  ;; Increase scrollback buffer
  (setq vterm-max-scrollback 5000)
  ;; Ensure terminal type is correct
  (setq vterm-term-environment-variable "xterm-256color")

  ;; -------------------------------
  ;; Arrow keys & Evil mode fix
  ;; -------------------------------
  (add-hook 'vterm-mode-hook
            (lambda ()
              ;; Always enter insert state
              (when (fboundp 'evil-insert-state)
                (evil-insert-state))
              ;; Let all keys pass to the terminal
              (setq-local vterm-keymap-exceptions nil)
              ;; Optional: improve scrolling in terminal
              (setq-local term-scroll-show-maximum-output t)))

  ;; -------------------------------
  ;; History navigation (backup)
  ;; -------------------------------
  (define-key vterm-mode-map (kbd "M-p") #'vterm-send-up)
  (define-key vterm-mode-map (kbd "M-n") #'vterm-send-down)

  ;; -------------------------------
  ;; Optional: sudo helper
  ;; -------------------------------
  (defun my/vterm-sudo ()
    "Open a vterm buffer with sudo privileges."
    (interactive)
    (let ((vterm-buffer-name "*vterm-sudo*"))
      (vterm)
      (vterm-send-string "sudo -i")
      (vterm-send-return)))

  ;; -------------------------------
  ;; Optional: copy/paste bindings
  ;; -------------------------------
  (with-eval-after-load 'vterm
    (define-key vterm-mode-map (kbd "C-c C-c") #'vterm-copy-mode)
    (define-key vterm-mode-map (kbd "C-c C-v") #'vterm-yank)))

#+end_src


** Vterm-Toggle
[[https://github.com/jixiuf/vterm-toggle][Vterm-toggle]] toggles between the vterm buffer and whatever buffer you are editing.
#+begin_src emacs-lisp
(use-package vterm-toggle
  :after vterm
  :config
  ;; When running programs in Vterm and in 'normal' mode, make sure that ESC
  ;; kills the program as it would in most standard terminal programs.
  (evil-define-key 'normal vterm-mode-map (kbd "<escape>") 'vterm--self-insert)
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                     (let ((buffer (get-buffer buffer-or-name)))
                       (with-current-buffer buffer
                         (or (equal major-mode 'vterm-mode)
                             (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                  (display-buffer-reuse-window display-buffer-at-bottom)
                  ;;(display-buffer-reuse-window display-buffer-in-direction)
                  ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                  ;;(direction . bottom)
                  ;;(dedicated . t) ;dedicated is supported in emacs27
                  (reusable-frames . visible)
                  (window-height . 0.4))))

#+end_src

* SUDO Edit
sudo-edit gives us the ability to open files with sudo privileges or switch over to editing with sudo privileges if we initially opened the file without such privileges.
#+begin_src emacs-lisp
(use-package sudo-edit)

#+end_src





* THEME
#+begin_src emacs-lisp

;; The first line below designates the directory where will place all of our custom-made themes, which I have created only one (dtmacs).  You can create your own Emacs themes with the help of the Emacs Theme Editor.  I am also installing doom-themes because it contains a huge collection of themes.  M-x load-theme will list all of the themes available. 

(add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")

(use-package doom-themes
  :config
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  ;; Sets the default theme to load!!! 
  (load-theme 'doom-one t)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
   (doom-themes-neotree-config)
  ;; Corrects (and improves) org-mode's native fontification.
   (doom-themes-org-config))

#+end_src

* TL;DR
#+begin_src emacs-lisp
(use-package tldr)

#+end_src

* Transparency
With Emacs version 29, true transparency has been added.  I have turned transparency off by setting the alpha to ‘100’.  If you want some slight transparency, try setting alpha to ‘90’.  Of course, if you set alpha to ‘0’, the background of Emacs would completely transparent.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background
 . 100)) ;; For all new frames henceforth

#+end_src


* WHICH-KEY
#+begin_src emacs-lisp
(use-package which-key
  :init
    (which-key-mode 1)
  :diminish
  :config
  (setq which-key-side-window-location 'bottom
	  which-key-sort-order #'which-key-key-order-alpha
	  which-key-allow-imprecise-window-fit nil
	  which-key-sort-uppercase-first nil
	  which-key-add-column-padding 1
	  which-key-max-display-columns nil
	  which-key-min-display-lines 6
	  which-key-side-window-slot -10
	  which-key-side-window-max-height 0.25
	  which-key-idle-delay 0.8
	  which-key-max-description-length 25
	  which-key-allow-imprecise-window-fit nil
	  which-key-separator " → " ))

#+end_src

* Custom Functions
#+begin_src emacs-lisp
;; --- Custom functions ---
(defun my/org-inline-paste ()
  "Paste latest kill-ring inline in Org."
  (interactive)
  (insert (current-kill 0)))

;; --- Evil + Org keybindings ---
(with-eval-after-load 'evil
  (evil-define-key 'normal org-mode-map
    (kbd "p") #'my/org-inline-paste
    (kbd "C-p") #'evil-paste-after))


#+end_src

#+begin_src emacs-lisp
;;This function automatically makes shell scripts executable when you save them if they sart with #1/bin/bash
;;Whenever a file is saved with #! (shebang), Emacs will automatically make it executable
(defun my/make-shell-script-executable ()
  "Make a shell script executable if it starts with a shebang."
  (when (and buffer-file-name
             ;; Ensure the file really starts with shebang
             (save-excursion
               (goto-char (point-min))
               (looking-at-p "^#!"))
             ;; Ensure the file ends with Unix line endings
             (not (eq buffer-file-coding-system 'unix)))
    (set-file-modes buffer-file-name #o755)
    (message "✅ Made %s executable" buffer-file-name)))

;; Add the hook after save
(add-hook 'after-save-hook #'my/make-shell-script-executable)

#+end_src

#+begin_src emacs-lisp
  ;; Make Evil stay in insert mode automatically in terminal buffers
  (with-eval-after-load 'evil
    (add-to-list 'evil-insert-state-modes 'vterm-mode)
    (add-to-list 'evil-insert-state-modes 'term-mode))

  (defun my/evil-insert-in-term ()
    "Force insert mode in terminal buffers."
    (when (derived-mode-p 'vterm-mode 'term-mode)
      (evil-insert-state)))

  (add-hook 'vterm-mode-hook #'my/evil-insert-in-term)
  (add-hook 'term-mode-hook #'my/evil-insert-in-term)

  ;; Optional: set default shell for vterm
  (setq vterm-shell "/bin/bash")

#+end_src















