#!/usr/bin/env bash
# 
# Install Docker before running scripts:
# sudo apt update
# sudo apt install docker.io
# sudo systemctl enable --now docker
# sudo usermod -aG docker "$USER"
#
#
# setup-searxng.sh - Set up a local SearXNG instance for use with gptel/MCP.
#
# Idempotent: safe to re-run. Will recreate the container if it already exists.
#
# Usage:
#   ./setup-searxng.sh              # install and start
#   ./setup-searxng.sh --uninstall  # stop and remove container + config

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
CONTAINER_NAME="searxng"
HOST_PORT="8888"
CONFIG_DIR="${SEARXNG_CONFIG_DIR:-$HOME/.config/searxng}"
IMAGE="searxng/searxng:latest"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { printf '\033[1;34m[*]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || err "Required command not found: $1"
}

# ---------------------------------------------------------------------------
# Uninstall path
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--uninstall" ]]; then
  log "Stopping and removing container '$CONTAINER_NAME'..."
  docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
  log "Removing config directory $CONFIG_DIR..."
  rm -rf "$CONFIG_DIR"
  log "Done. SearXNG has been removed."
  exit 0
fi

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------
log "Checking prerequisites..."
need_cmd docker

if ! docker info >/dev/null 2>&1; then
  err "Cannot talk to the Docker daemon. Is it running? Are you in the 'docker' group?
  Try: sudo systemctl start docker
       sudo usermod -aG docker \$USER  (then log out and back in)"
fi

# Check port availability
if ss -tln 2>/dev/null | grep -q ":${HOST_PORT} "; then
  warn "Port ${HOST_PORT} is already in use. If it's not the existing SearXNG container,"
  warn "you'll need to either stop the conflicting service or change HOST_PORT in this script."
fi

# ---------------------------------------------------------------------------
# Config directory + settings.yml
# ---------------------------------------------------------------------------
log "Setting up config directory at $CONFIG_DIR..."
mkdir -p "$CONFIG_DIR"

SETTINGS_FILE="$CONFIG_DIR/settings.yml"
if [[ ! -f "$SETTINGS_FILE" ]]; then
  log "Generating new settings.yml with a random secret key..."
  # Generate a random secret. Fall back to /dev/urandom if openssl missing.
  if command -v openssl >/dev/null 2>&1; then
    SECRET=$(openssl rand -hex 32)
  else
    SECRET=$(head -c 32 /dev/urandom | xxd -p -c 32)
  fi

  cat > "$SETTINGS_FILE" <<EOF
# SearXNG configuration - generated by setup-searxng.sh
# See https://docs.searxng.org/admin/settings/index.html for all options.

use_default_settings: true

general:
  instance_name: "Local SearXNG"

server:
  secret_key: "${SECRET}"
  limiter: false           # disable rate limiting for local single-user use
  image_proxy: false
  bind_address: "0.0.0.0"
  port: 8080

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json                 # required for MCP / API access

ui:
  static_use_hash: true

# Tweak which engines are active. The defaults are usually fine; uncomment
# and edit to disable noisy or low-quality engines.
# engines:
#   - name: wikipedia
#     disabled: false
EOF
  log "Wrote $SETTINGS_FILE"
else
  log "Existing settings.yml found - leaving it alone."
  # Sanity check: make sure JSON is enabled
  if ! grep -q "json" "$SETTINGS_FILE"; then
    warn "Your settings.yml does not appear to enable the JSON format."
    warn "The MCP server will not work without it. Add 'json' under search.formats."
  fi
fi

# ---------------------------------------------------------------------------
# Pull image
# ---------------------------------------------------------------------------
log "Pulling latest SearXNG image..."
docker pull "$IMAGE"

# ---------------------------------------------------------------------------
# (Re)create container
# ---------------------------------------------------------------------------
if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  log "Removing existing container '$CONTAINER_NAME'..."
  docker rm -f "$CONTAINER_NAME" >/dev/null
fi

log "Starting new container '$CONTAINER_NAME' on port $HOST_PORT..."
docker run -d \
  --name "$CONTAINER_NAME" \
  --restart unless-stopped \
  -p "127.0.0.1:${HOST_PORT}:8080" \
  -v "${CONFIG_DIR}:/etc/searxng" \
  -e "BASE_URL=http://localhost:${HOST_PORT}/" \
  -e "INSTANCE_NAME=local" \
  "$IMAGE" >/dev/null

# ---------------------------------------------------------------------------
# Wait for it to come up
# ---------------------------------------------------------------------------
log "Waiting for SearXNG to start..."
for i in {1..20}; do
  if curl -fs "http://localhost:${HOST_PORT}/" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

# ---------------------------------------------------------------------------
# Verify JSON API
# ---------------------------------------------------------------------------
log "Verifying JSON API..."
if curl -fs "http://localhost:${HOST_PORT}/search?q=test&format=json" \
     | grep -q '"results"'; then
  log "JSON API working."
else
  warn "JSON API check failed. Container logs:"
  docker logs --tail 30 "$CONTAINER_NAME" >&2
  err "SearXNG is running but JSON queries are not returning results. Check settings.yml."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
cat <<EOF

✓ SearXNG is running at http://localhost:${HOST_PORT}/

  Container:   ${CONTAINER_NAME}
  Config:      ${CONFIG_DIR}/settings.yml
  Logs:        docker logs -f ${CONTAINER_NAME}
  Stop:        docker stop ${CONTAINER_NAME}
  Start:       docker start ${CONTAINER_NAME}
  Uninstall:   $0 --uninstall

Add this to your Emacs MCP config:

  ("searxng" .
   (:command "npx"
    :args ("-y" "mcp-searxng")
    :env (("SEARXNG_URL" . "http://localhost:${HOST_PORT}"))))

EOF
